@extends('layouts.master')

@section('header')
    <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content d-sm-flex">
            <div class="page-title">
                <h4>@lang('cms.User Create')</h4>
            </div>
        </div>

        <div class="breadcrumb-line breadcrumb-line-light header-elements-sm-inline">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{ route('cms.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>
                        @lang('cms.Home')</a>
                    <a href="{{ route('cms.store.users.list') }}" class="breadcrumb-item">@lang('cms.User')</a>
                    <a href="#" class="breadcrumb-item active">@lang('cms.Create')</a>
                </div>

                <a href="#" class="header-elements-toggle text-body d-sm-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h2>Add User</h2>
        </div>
        <div class="card-body">
            <form id="form" action="{{ route('cms.store.users.store') }}" class="row" method="POST">
                @csrf
                <div class="col-sm-12 col-lg-6">
                    <div class="row">
                        <div class="col-12">
                            <h3>Basic Information</h3>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Email</label>
                            <input type="text" name="email" value="{{ old('email') }}" class="form-control">
                        </div>
                        <div class="form-group col-12">
                            @if(isProductionMode())
                                <label class="text-muted" for="">Password</label>
                                <input type="password" disabled class="form-control">
                                <span class="text-muted">*) Password will be autogenerated</span>
                            @else
                                <label class="text-muted" for="">Password</label>
                                <input type="password" disabled class="form-control">
                                <span class="text-muted">*) You cannot set password in this environment</span>
                            @endif
                        </div>
                        <div class="form-group col-12">
                            <label for="">Full Name</label>
                            <input type="text" name="full_name" value="{{ old('full_name') }}" class="form-control">
                        </div>
                        <div class="form-group col-12">
                            <label for="">Phone</label>
                            <input type="text" name="phone" value="{{ old('phone') }}" class="form-control">
                        </div>
                        <div class="form-group col-12">
                            <label for="">Gender</label>
                            <select name="gender" class="form-control" id="">
                                <option value="MALE" {{ old('gender') == 'MALE' ? 'selected' : '' }}>Male</option>
                                <option value="FEMALE" {{ old('gender') == 'FEMALE' ? 'selected' : '' }}>Female
                                </option>
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Description</label>
                            <textarea name="description" class="form-control" id="" cols="30" rows="10">{{ old('description') }}</textarea>
                        </div>
                        <div class="form-group col-12">
                            <label for="status-select">Status</label>
                            <select name="active" class="form-control" id="status-select">
                                <option value="1" {{ isset($user['active']) && $user['active'] == '1' ? 'selected' : '' }}>Active</option>
                                <option value="0" {{ isset($user['active']) && $user['active'] == '0' ? 'selected' : '' }}>Inactive</option>
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <div class="form-check col-12">
                                <input id="checkbox-sandbox-pg" 
                                    type="checkbox" 
                                    name="sandbox_pg" 
                                    class="form-check-input" 
                                    @if(isset($user['settings']) && in_array('PG_SANDBOX', $user['settings'])) checked @endif
                                    @if(isset($user['active']) && $user['active'] == '0') disabled @endif>
                                <label for="checkbox-sandbox-pg" class="form-check-label">Activate Sandbox Payment Gateway</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-lg-6">
                    <div class="row">
                        <div class="col-12">
                            <h3>Role Information</h3>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Role</label>
                            <select name="roles[]" form="form" id="role-select" class="form-control" multiple="multiple">
                                @foreach ($roles as $role)
                                    <option value="{{ json_encode($role) }}">{{ $role['name'] }} - {{ $role['target_type'] }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Partner</label>
                            <select name="target_partner[]" form="form" id="partner-select" class="form-control select2" id=""></select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Merchant Branch</label>
                            <select name="target_merchant_branch[]" form="form" id="merchant-branch-select" class="form-control select2" id=""></select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Beneficiary</label>
                            <select name="target_beneficiary[]" form="form" id="beneficiary-select" class="form-control select2" id=""></select>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-3 col-12">
                    <button form="form" class="btn btn-primary">Save</button>
                    <a href="{{ route('cms.store.users.list') }}" class="btn btn-dark">Cancel</a>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('post_scripts')
    <script>
        $(document).ready(function() {
            const statusSelect = document.getElementById('status-select');
            const sandboxCheckbox = document.getElementById('checkbox-sandbox-pg');

            statusSelect.addEventListener('change', function () {
                if (statusSelect.value === '0') {
                    sandboxCheckbox.checked = false;
                    sandboxCheckbox.disabled = true; 
                } else {
                    sandboxCheckbox.disabled = false;
                }
            });

            statusSelect.dispatchEvent(new Event('change'));
            $('#role-select').select2({
                placeholder: 'Select Role',
            });

            $('#partner-select').select2({
                ajax: {
                    url: "/store/partners",
                    type: "GET",
                    dataType: 'json',
                    data: function(params) {
                        return {
                            search: params.term,
                            page: params.page
                        };
                    },
                    processResults: function(data, params) {
                        params.page = params.page || 1;

                        let result = data.result.map(function(item) {
                            item.id = item.id;
                            item.text = item.name;
                            return item;
                        });

                        return {
                            results: result
                        };
                    }
                },
                placeholder: 'Search partner',
                minimumInputLength: 1,
                multiple: true
            })
            $('#merchant-branch-select').select2({
                ajax: {
                    url: "/store/merchant_branches",
                    type: "GET",
                    dataType: 'json',
                    data: function(params) {
                        return {
                            search: params.term,
                            page: params.page
                        };
                    },
                    processResults: function(data, params) {
                        params.page = params.page || 1;

                        let result = data.result.map(function(item) {
                            item.id = item.id;
                            item.text = item.name;
                            return item;
                        });

                        return {
                            results: result
                        };
                    }
                },
                placeholder: 'Search merchant branch',
                minimumInputLength: 1,
                multiple: true
            });
            $('#beneficiary-select').select2({
                ajax: {
                    url: "/store/beneficiaries",
                    type: "GET",
                    dataType: 'json',
                    data: function(params) {
                        return {
                            search: params.term,
                            page: params.page
                        };
                    },
                    processResults: function(data, params) {
                        params.page = params.page || 1;

                        let result = data.result.map(function(item) {
                            item.id = item.id;
                            item.text = item.name;
                            return item;
                        });

                        return {
                            results: result
                        };
                    }
                },
                placeholder: 'Search beneficiary',
                minimumInputLength: 1,
                multiple: true
            });
        });
    </script>
@endsection
