@extends('layouts.master')

@section('header')
    <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content d-sm-flex">
            <div class="page-title">
                <h4>@lang('cms.User Edit')</h4>
            </div>
        </div>

        <div class="breadcrumb-line breadcrumb-line-light header-elements-sm-inline">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{ route('cms.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>
                        @lang('cms.Home')</a>
                    <a href="{{ route('cms.store.users.list') }}" class="breadcrumb-item">@lang('cms.User')</a>
                    <a href="#" class="breadcrumb-item active">@lang('cms.Edit')</a>
                </div>

                <a href="#" class="header-elements-toggle text-body d-sm-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h2>Edit User</h2>
        </div>
        <div class="card-body">
            <form id="form" action="{{ route('cms.store.users.update', $user['id']) }}" class="row" method="POST">
                @csrf
                @method('put')
                <div class="col-sm-12 col-lg-6">
                    <div class="row">
                        <div class="col-12">
                            <h3>Basic Information</h3>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Email</label>
                            <input type="text" name="email" value="{{ @$user['email'] }}" class="form-control">
                        </div>
                        <div class="form-group col-12">
                            <label class="text-muted" for="">Password</label>
                            <input type="password" disabled class="form-control">
                            <span class="text-muted">*) Password will be autogenerated</span>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Full Name</label>
                            <input type="text" name="full_name" value="{{ @$user['full_name'] }}" class="form-control">
                        </div>
                        <div class="form-group col-12">
                            <label for="">Phone</label>
                            <input type="text" name="phone" value="{{ @$user['phone'] }}" class="form-control">
                        </div>
                        <div class="form-group col-12">
                            <label for="">Gender</label>
                            <select name="gender" class="form-control" id="">
                                <option value="MALE" {{ @$user['gender'] == 'MALE' ? 'selected' : '' }}>Male</option>
                                <option value="FEMALE" {{ @$user['gender'] == 'FEMALE' ? 'selected' : '' }}>Female
                                </option>
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Description</label>
                            <textarea name="description" class="form-control" id="" cols="30" rows="10">{{ @$user['description'] }}</textarea>
                        </div>
                        <div class="form-group col-12">
                            <label for="status-select">Status</label>
                            <select name="active" class="form-control" id="status-select">
                                <option value="1" {{ $user['active'] == '1' ? 'selected' : '' }}>Active</option>
                                <option value="0" {{ $user['active'] == '0' ? 'selected' : '' }}>Inactive</option>
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <div class="form-check col-12">
                                <input id="checkbox-sandbox-pg" 
                                    type="checkbox" 
                                    name="sandbox_pg" 
                                    class="form-check-input" 
                                    @if(in_array('PG_SANDBOX', $user['settings'])) checked @endif
                                    @if($user['active'] == '0') disabled @endif>
                                <label for="checkbox-sandbox-pg" class="form-check-label">Activate Sandbox Payment Gateway</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-lg-6">
                    <div class="row">
                        <div class="col-12">
                            <h3>Role Information</h3>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Role</label>
                            <select name="roles[]" form="form" id="role-select" class="form-control select2" id="">
                                @foreach ($roles as $role)
                                <option value="{{ $role }}">{{ explode("|", $role)[1] }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Partner</label>
                            <select name="target_partner[]" form="form" id="partner-select" class="form-control select2" id="">
                                @foreach ($partners as $partner)
                                    <option value="{{ $partner['id'] }}">{{ $partner['name'] }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Merchant Branch</label>
                            <select name="target_merchant_branch[]" form="form" id="merchant-branch-select" class="form-control select2" id="">
                                @foreach ($merchantBranches as $branch)
                                <option value="{{ $branch['id'] }}">{{ $branch['name'] }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <label for="">Assign Beneficiary</label>
                            <select name="target_beneficiary[]" form="form" id="beneficiary-select" class="form-control select2" id="">
                                @foreach ($customers as $customer)
                                <option value="{{ $customer['id'] }}">{{ $customer['name'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-3 col-12">
                    <button type="submit" form="form" class="btn btn-primary">Save</button>
                    <a href="{{ route('cms.store.users.list') }}" class="btn btn-dark">Cancel</a>
                </div>
            </div>
        </div>

        <div class="modal fade" id="resetPass" tabindex="-1" role="dialog" aria-labelledby="resetPassword"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form action="{{ route("cms.store.users.reset", @$user['id']) }}" id="reset-form" method="POST">
                        @csrf
                        <div class="modal-header">
                            <div class="input-group row justify-content-center w-100">
                                <h5 class="modal-title w-100">Reset Password</h5>
                            </div>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="text-center mr-3 mb-1">Insert Your Password</div>
                            <div class="input-group mb-3 row justify-content-center w-100">
                                <input id="password" name="password" form="reset-form" type="password" required value=""
                                    class="input form-control col-sm-6 w-100" />
                            </div>
                        </div>
                        <div>
                            <p class="text-center"><em>By clicking Reset,you will reset password for this account
                                {{  @$user['username'] }} to system default value</em></p>
                        </div>
                        <div class="modal-footer justify-content-center">
                            <button type="submit" form="reset-form" class="btn btn-primary">Change</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal-toggle-active" tabindex="-1" role="dialog"
            aria-labelledby="demoModalLabel" aria-hidden="true">
            <form id="modal-confirmation-form" class="modal-dialog"
                role="document" method="post" action="{{ route('cms.store.users.toggle.active', $user['id']) }}">
                @csrf
                <input id="modal-confirmation-input" name="id" type="hidden" value="{{ $user['id'] }}">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="demoModalLabel">Confirmation</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure to {{ empty($user['active']) ? 'activate' : 'deactivate' }} {{ $user['username'] }}?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('post_scripts')
    <script>
        $(document).ready(function() {
            const statusSelect = document.getElementById('status-select');
            const sandboxCheckbox = document.getElementById('checkbox-sandbox-pg');

            statusSelect.addEventListener('change', function () {
                if (statusSelect.value === '0') {
                    sandboxCheckbox.checked = false;
                    sandboxCheckbox.disabled = true; 
                } else {
                    sandboxCheckbox.disabled = false;
                }
            });

            statusSelect.dispatchEvent(new Event('change'));

            $('#role-select').select2({
                placeholder: 'Select Role',
                multiple: true
            });

            $('#partner-select').select2({
                ajax: {
                    url: "/store/partners",
                    type: "GET",
                    dataType: 'json',
                    data: function(params) {
                        return {
                            search: params.term,
                            page: params.page || 1
                        };
                    },
                    processResults: function(data, params) {
                        params.page = params.page || 1;
                        let more = data.more;
                        let result = data.result.map(function(item) {
                            item.id = item.id;
                            item.text = item.name;
                            return item;
                        });

                        return {
                            pagination: {
                                more: more
                            },
                            results: result
                        };
                    }
                },
                placeholder: 'Search partner',
                minimumInputLength: 1,
                multiple: true
            })
            $('#merchant-branch-select').select2({
                ajax: {
                    url: "/store/merchant_branches",
                    type: "GET",
                    dataType: 'json',
                    data: function(params) {
                        return {
                            search: params.term,
                            page: params.page || 1
                        };
                    },
                    processResults: function(data, params) {
                        let more = data.more;
                        params.page = params.page || 1;

                        let result = data.result.map(function(item) {
                            item.id = item.id;
                            item.text = item.name;
                            return item;
                        });

                        return {
                            pagination: {
                                more: more
                            },
                            results: result,
                        };
                    }
                },
                placeholder: 'Search merchant branch',
                minimumInputLength: 1,
                multiple: true
            });
            $('#beneficiary-select').select2({
                ajax: {
                    url: "/store/beneficiaries",
                    type: "GET",
                    dataType: 'json',
                    data: function(params) {
                        return {
                            search: params.term,
                            page: params.page || 1
                        };
                    },
                    processResults: function(data, params) {
                        params.page = params.page || 1;
                        let more = data.more;
                        let result = data.result.map(function(item) {
                            item.id = item.id;
                            item.text = item.name;
                            return item;
                        });

                        return {
                            pagination: {
                                more: more
                            },
                            results: result
                        };
                    }
                },
                placeholder: 'Search beneficiary',
                minimumInputLength: 1,
                multiple: true
            });

            let userRoles = @json($userRoles);
            $('#role-select').val(userRoles).trigger('change')
            $('#partner-select').val(@json(array_column($partners, 'id'))).trigger('change')
            $('#merchant-branch-select').val(@json(array_column($merchantBranches, 'id'))).trigger('change')
            $('#beneficiary-select').val(@json(array_column($customers, 'id'))).trigger('change')
        });

        function escapeHtml(text) {
            var map = {
                '&': '&amp;',
                '<': '&lt;',
                '>': '&gt;',
                '"': '&quot;',
                "'": '&#039;'
            };

            return text.replace(/[&<>"']/g, function(m) { return map[m]; });
        }
    </script>
@endsection
