<?php

namespace App\Helpers;

class DisbursementHelper
{
    const BCA_MAX_TRANSFER_AMOUNT = "BCA_MAX_TRANSFER_AMOUNT";
    const BCA_TRANSFER_FRACTIONS_AMOUNT = "BCA_TRANSFER_FRACTIONS_AMOUNT";
    const NON_BCA_MAX_TRANSFER_AMOUNT = "NON_BCA_MAX_TRANSFER_AMOUNT";
    const NON_BCA_TRANSFER_FRACTIONS_AMOUNT = "NON_BCA_TRANSFER_FRACTIONS_AMOUNT";
}
