<?php
/**
 * Created by PhpStorm.
 * User: Lorentzo
 * Date: 04-Feb-22
 * Time: 11:04
 */

namespace App\Helpers;


class UserWithdrawalHelper {

    const STATUS_PENDING = "PENDING";
    const STATUS_TRANSACTION_CREATED = "TRANSACTION_CREATED";
    const STATUS_CASHOUT_CREATED = "CASHOUT_CREATED";
    const STATUS_CASHOUT_FAILED = "CASHOUT_FAILED";
    const STATUS_EXECUTION_CREATED = "EXECUTION_CREATED";
    const STATUS_EXECUTION_SUCCESS = "EXECUTION_SUCCESS";
    const STATUS_EXECUTION_TIMEOUT = "EXECUTION_TIMEOUT";
    const STATUS_EXECUTION_ON_HOLD = "EXECUTION_ON_HOLD";
    const STATUS_ON_PROCESS_CHECK_STATUS = "ON_PROCESS_CHECK_STATUS";
    const STATUS_ON_PROCESS_YUKK_CASH_TO_SETTLEMENT = "ON_PROCESS_YUKK_CASH_TO_SETTLEMENT";
    const STATUS_SUCCESS_YUKK_CASH_TO_SETTLEMENT = "SUCCESS_YUKK_CASH_TO_SETTLEMENT";
    const STATUS_FAILED_YUKK_CASH_TO_SETTLEMENT = "FAILED_YUKK_CASH_TO_SETTLEMENT";
    const STATUS_ON_PROCESS_SETTLEMENT_TO_WD = "ON_PROCESS_SETTLEMENT_TO_WD";
    const STATUS_SUCCESS_SETTLEMENT_TO_WD = "SUCCESS_SETTLEMENT_TO_WD";
    const STATUS_FAILED_SETTLEMENT_TO_WD = "FAILED_SETTLEMENT_TO_WD";
    const STATUS_ON_PROCESS_WD_TO_DSP = "ON_PROCESS_WD_TO_DSP";
    const STATUS_SUCCESS_WD_TO_DSP = "SUCCESS_WD_TO_DSP";
    const STATUS_FAILED_WD_TO_DSP = "FAILED_WD_TO_DSP";
    const STATUS_ON_PROCESS_WD_TO_BENEF = "ON_PROCESS_WD_TO_BENEF";
    const STATUS_SUCCESS_WD_TO_BENEF = "SUCCESS_WD_TO_BENEF";
    const STATUS_FAILED_WD_TO_BENEF = "FAILED_WD_TO_BENEF";
    const STATUS_ON_PROCESS_REFUND_WD_TO_SETTLEMENT = "ON_PROCESS_REFUND_WD_TO_SETTLEMENT";
    const STATUS_FAILED_REFUND_WD_TO_SETTLEMENT = "FAILED_REFUND_WD_TO_SETTLEMENT";
    const STATUS_FAILED_REFUND_SETTLEMENT_TO_YUKK_CASH = "FAILED_REFUND_SETTLEMENT_TO_YUKK_CASH";
    const STATUS_ON_PROCESS_REFUND_SETTLEMENT_TO_YUKK_CASH = "ON_PROCESS_REFUND_SETTLEMENT_TO_YUKK_CASH";

    const BANK_TYPE_BCA = "BCA";
    const BANK_TYPE_NON_BCA = "NON_BCA";
}