@extends('layouts.master')

@section('header')
    <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content d-sm-flex">
            <div class="page-title">
                {{--<h4><span class="font-weight-semibold">Seed</span> - Static layout</h4>--}}
                <h4>Partner Credentials</h4>
            </div>

            <div class="my-sm-auto ml-sm-auto mb-3 mb-sm-0">
                {{--<button type="button" class="btn btn-primary w-100 w-sm-auto">Button</button>--}}
            </div>
        </div>

        <div class="breadcrumb-line breadcrumb-line-light header-elements-sm-inline">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{ route("cms.index") }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> @lang("cms.Home")</a>
                    <a href="{{ route("cms.partner.transaction_pg.list") }}" class="breadcrumb-item">Partner Credentials</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">@lang("cms.Transaction Payment Gateway")</h5>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group row">
                        <label class="col-lg-12 col-form-label">
                            Please use this Client ID and Client Secret to get your access token.
                            You will need to know your Access Token (Client ID and Client Secret) and Merchant ID (MID) to communicate with YUKK.
                            Please use the Development server while you are still in development
                        </label>
                    </div>
                    <div class="form-group row">
                        <h2 class="col-lg-12 col-form-label font-weight-bold">API Keys</h2>
                    </div>
                    <div class="form-group row border border-light w-100 p-2">
                        <div class="row w-100">
                            <div class="col-3">
                                Client ID
                            </div>
                            <div class="col-auto">
                                {{ $clientId ?? '-'}}
                            </div>
                        </div>
                        <hr>
                        <div class="row w-100">
                            <div class="col-3">
                                Client Secret
                            </div>
                            <div class="col-auto">
                                {{ $clientSecret ?? '-' }}
                            </div>
                        </div>
                        <hr>
                        <div class="row w-100">
                            <div class="col-3">
                                MID
                            </div>
                            <div class="col-9 w-100">
                                @if($mids)
                                <div class="row w-100 p-2 table table-bordered">
                                    @foreach($mids as $mid)
                                    <div class="col-3">
                                        {{ data_get($mid, 'merchant_branch.name') ?? '-' }}
                                    </div>
                                    <div class="col-9">
                                        {{ data_get($mid, 'mid', '-') ?? '-' }}
                                    </div>
                                    @endforeach
                                </div>
                                @else
                                -
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group bg-warning row">
                        <label class="col-lg-12 col-form-label">
                            This keys is auto generated by system and should not be changed.
                        </label>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-12 col-form-label">
                            *) If the fields is empty please contact our support.
                        </label>
                    </div>

                    <div class="form-group row">
                        <h2 class="col-lg-12 col-form-label font-weight-bold">Tech Docs</h2>
                    </div>
                    <div class="form-group row">
                        <a href="{{ config('payment_gateway.documents.postman') }}" class="btn btn-primary" target="_blank">
                            <i class="icon-download"></i> &nbsp;
                            Download
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $(".dataTable").DataTable();
        });
    </script>
@endsection